### PR TITLE
Convert codebase to TypeScript

### LINKED ISSUE #120: Document main data structures and transformations for class/schedule data

### LINKED ISSUE #126: PropTypes for every component

### PR DESCRIPTION
**Pull request by EricPedley**
spent too much time making this. Used Google Docs, inserted gif and recorded on ScreenToGif

Implementation Plan: rename all js files to ts or tsx depending on whether it contains components or not, then fix all the compiler errors.

This change is too big for one PR so I'm going to split it up into child PRs.
- [x] Convert AppBar: #412
- [x] Convert Calendar: #420 
- [x] Convert Map: #421 
- [x] Convert AddedCourses and SectionTable: #423
- [x] Convert CoursePane and SearchForm: #439
- [x] Convert AppStore and helpers: #444 
- [x] Backport and convert existing changes from `main`: #450 
- [x] Fix all `@ts-ignore` workarounds (e.g. instances of `openSnackbar`) and TODOS related to TS or open new issues for anything to procrastinate on
- [x] Update code style tooling per [here](https://gist.github.com/ecxyzzy/dd7989bdf546942a6b7655602d4e8f79)
- [x] Lint and ship! :rocket:

All of these sub-tasks can also include changes to files outside of their respective folders if necessary but should try to limit the scope to just one section.

Associated dev log: https://github.com/icssc/AntAlmanac/wiki/The-Great-AntAlmanac-TypeScript-Rewritening%E2%84%A2

## Test Plan
Verify successful compilation on preview deployments and click around testing website features

## Issues
Closes #120 and #126

### CODE REVIEW

**Comment by EricPedley** [comment]
Of course the deployment doesn't work 😑

**Comment by EricPedley** [comment]
Meant to add reviewers on #420. Oops.

**Comment by ecxyzzy** [comment]
> Run linter and add `ts` and `tsx` files to the "lint-staged" section of `package.json`

Would it be within scope to update our code style tooling? The versions of husky/lint-staged/prettier we use are pretty outdated, and it complains every time a commit is made because we're not supposed to run `git add` in the lint-staged config (see below).
Demonstration of the warning raised by our current lint-staged configuration.

Might also be appropriate to start using ESLint to enforce code quality (e.g. variables implicitly typed as `any` that might be problematic, c.f. the discussion in #421), but it is quite slow in my experience.

**Comment by EricPedley** [comment]
Yeah, we can update our code styling tools with this PR. If ESLint is slow maybe we can just run it as a github action on PRs and not add it to our package to run locally. https://github.com/eslint/github-action

Also, cool powerline setup
patrick bateman very impressive gif

**Comment by Voark** [comment]
If we're using it as a precommit hook I feel like that's not too bad because it won't be run often and also it's easier to fix issues then dealing with a github action ESLint run failure.

**Comment by EricPedley** [comment]
That's a valid point. We can try the pre-commit hook and just feel if its performance is good enough and keep the GitHub action in mind as a backup. I'll handle that once I get to that task but you guys can feel free to do it first if you want.

**Comment by Voark** [comment]
Accidentally pushed to this branch instead of making my own

**Comment by EricPedley** [comment]
All that needs review are the commits since merging #450. You don't have to look at the whole thing since all the squashed commits up until this point have been reviewed.

**Comment by EricPedley** [comment]
Ok it's ready for review for real now. @Voark @Douglas-Hong

**Review by Douglas-Hong — APPROVED** [review]
Everything looks good to me! I tested most of the features and the functionality is the same.

There are a couple of bugs I found, but the bugs are also in production and we can deal with them later. The "All" tab on the map  sometimes doesn't show any pins if one class's location is TBA. Additionally, pressing backspace while typing a schedule name also triggers the back button for the right pane. I'll make issues for them.

**Comment by ChaseC99** [comment]
This is a historic moment for AntAlmanac !!!

**Pull request merged**
