### PR TITLE
Change schedule selector to dropdown

### PR DESCRIPTION
**Pull request by ChaseC99**
## Summary
Change schedule switcher to a dropdown menu.
schedule-dropdown

## Test Plan
- Add a class to each schedule, verify they appear correctly
- Add a custom event to each schedule, verify they appear correctly
- Save and reload the schedules, verify the events persist

## Future Followup (Optional)
Later on, we'll probably swap "Schedule {1-4}" out for named schedules associated with an account.

### CODE REVIEW

**Comment by braedons** [comment]
image

This issue pops up when selecting schedule 5. There's also no option to add a custom class or searched-for class to schedule 5. Seems like it's there by mistake?

**Comment by ChaseC99** [comment]
Good catch - thanks. I'll try to reproduce this locally and figure out what's going on.

**Comment by ChaseC99** [comment]
Ah you're right; Schedule 5 was added by mistake! 

Before we only had schedules 1-4. The 5th one caused the index-out-of bounds error.

**Review by braedons — APPROVED** [review]
Everything looks good now! No errors found anymore.

**Pull request merged**
