### PR TITLE
Update Map & Routes When Changing Schedules

### LINKED ISSUE #566: Map locations don't update when changing schedules
See title.

## Reproduction

Have a profile with multiple schedules. Open the map. Change to another schedule.

## Issues
Possibly addressed by #563

### PR DESCRIPTION
**Pull request by KevinWu098**
## Summary

1. Maps and routes will now update properly on both Schedule Index and Calendar Event changes. 

Demonstrates map responsiveness to schedule change

Map responsiveness on event deletion

~~2. Added tooltip to Import button~~

~~Import Tooltip~~

~~3. Didn't realize I left it in, but sectionType will now be shown in the pop-up. This appears to already be addressed by #559 , so mb 😅. Our implementation differs only in where it's shown (Heading vs with the other information), but I'll defer 🙇‍♂️~~

## Test Plan

1. Confirmed that when swapping between Schedules 1 and 2, the map's markers would change accordingly. The same does occur for planned routes.

~~2. Verified that on hover, the tooltip with the appropriate message appears.~~

## Issues
Map does not play nice with the finals schedule, but that appears to occur regardless of my PR

Closes #566   ~~& #414~~

### CODE REVIEW

**Comment by KevinWu098** [comment]
1. Gifs and Images of changes have been added :)
2. Moved #567 PR description into the summary above as well

**Review by MinhxNguyen7 — APPROVED** [review]
Hi @KevinWu098, thanks for the contributions. The changes look good, and I've tested it locally. 

However, I'm not sure if @EricPedley is good with merging this because it violates "atomic commits". We squash all commits in a pull request into a single commit before merging it into main, and your PR contains two distinct changes (adding tooltip to import button and updating the map when the schedule changes). 

This fix to the map will be superseded by #563, but it's small enough and is somewhat important, so I think it should be taken while that's being developed.

**Comment by KevinWu098** [comment]
Sorry bout that @MinhxNguyen7 😅. I'm still getting the hang of Git and branches, so I ended up working on top of the import button PR

I'll get the hang of it for the next PR :)

**Review by EricPedley — CHANGES_REQUESTED** [review]
Merging this isn't too time-critical so I'm gonna ask you to interactive rebase and force-push this branch to exclude the tooltip changes. See this tutorial for help: https://www.youtube.com/watch?v=ElRzTuYln0M&t=254s

**Comment by KevinWu098** [comment]
@EricPedley I think I fixed it :), this PR should only have the Map bug fixes now!

**Review by ap0nia — APPROVED** [review]
Looks good, very cool

**Pull request merged**
