### PR TITLE
fix: typescript errors

### PR DESCRIPTION
**Pull request by ap0nia**
## Summary
Fix errors that appear when `tsc` is executed.

- There's one last error due to the schema for custom events, which will be rectified in #814

## Test Plan
Run `tsc`

### CODE REVIEW

**Review by EricPedley — CHANGES_REQUESTED** [review]
when I run TSC I get a bajillion errors still. Is this a problem with the code or is it just me? I noticed that some of the errors are stupid like "can't find (package that is already installed)", so maybe my `tsc` is broken?
image

**Comment by ap0nia** [comment]
There should only be one error for the custom events. Could you try removing all instances of `node_modules` and running `pnpm install` from the project root before running `pnpm tsc` in the `apps/antalamanc` directory again?

**Comment by EricPedley** [comment]
> There should only be one error for the custom events. Could you try removing all instances of `node_modules` and running `pnpm install` from the project root before running `pnpm tsc` in the `apps/antalamanc` directory again?

Ok that worked. Do u think its worth throwing this troubleshooting step in the docs somewhere?

**Comment by ap0nia** [comment]
Sure, I actually had one last update from the `update-config` branch that had a list of the frontend libraries we use and possible reasons why. I could re-open that branch and add these troubleshooting steps.

**Comment by EricPedley** [comment]
why reopen the branch instead of just creating a new one?

**Comment by ap0nia** [comment]
Misinput, yeah new branch.

**Review by EricPedley — APPROVED** [review]

**Pull request merged**
