### PR TITLE
Added a Tooltip to the Import button | Added Section Type to Calendar Popups

### LINKED ISSUE #414: Add tooltip to "Import" button
In the app bar, some of the items have tooltips explaining what the button does. For example, "Feedback" says "Give Us Feedback!"

image

"Import" is missing one though! 
Add a tooltip to the "Import" button that says "Import a schedule from your Study List" 

Hint: wrap `<ImportStudyList />` in a [`<Tooltip>`](https://mui.com/material-ui/react-tooltip/)

### PR DESCRIPTION
**Pull request by KevinWu098**
## Summary
Added a Tooltip to the Import Button ("Import a schedule from your Study List")

## Test Plan
- Verified that on hover, the tooltip with the appropriate message appears.

## Issues
Closes #414

### CODE REVIEW

**Comment by Voark** [comment]
Hi! Sorry but our CI/CD pipeline right now isn't configured to handle branches from outside our repo which is why the actions are failing. It shouldn't be a problem though because someone can review by just cloning and running locally.

**Comment by KevinWu098** [comment]
I pushed (?, the jargon is hard for me to remember right now) another (minor) improvement to this same branch

## Summary
Added Section type as another row of information on the additional info shown in popups on the courses in the Calendar.

## Test Plan
- Verified that on click, the tooltip with the new Section type information appears.

**Comment by EricPedley** [comment]
If you have extra time/energy I'd consider adding screenshots or gifs to the PR description to make it easier for the reviewer to see the intended effect of the change. Something like a before/after so that when they go to test it locally it's obvious what they're looking for and review goes faster. Same idea goes for #568 that you have open rn too.

**Comment by ap0nia** [comment]
I'm gonna close this PR because #568 covers these changes as well.

**Comment by EricPedley** [comment]
Reopening this because I'm asking him to rebase #568 to exclude these changes

**Comment by KevinWu098** [comment]
Closing this PR and reopening it so that I can PR from a new branch other than my main

**Pull request closed without merging**
