### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by uci-mars**
## Summary
fix type: devlop -> `develop`
https://www.merriam-webster.com/dictionary/develop

## Test Plan
read

## Future Followup (Optional)
write better

### CODE REVIEW

**Comment by uci-mars** [comment]
im helping

**Comment by ChaseC99** [comment]
boo stop stealing the fun from the kiddos

**Review by devsdevsdevs — CHANGES_REQUESTED** [review]
Gonna need some unit tests on this

**Review by ChaseC99 — APPROVED** [review]
smh now I have to hide another typo in the README for newbies to find

**Pull request merged**
