### PR TITLE
Small Fix on the Custom Event style

### LINKED ISSUE #821: Small Fix: Custom Event Style
## 1. Match the font style of custom event to the course events

Image

Image

## 2. Make all tool button showing description. (Deletion here has, but other two button don't have the feature)

Image

## 3. Showing the building under the custom event name

Image

### PR DESCRIPTION
**Pull request by stevenguyukai**
### 1. Marker description style for Custom Event match the course style
image

### 2. Showing the building name under the custom event name
image

### 3. Showing description of tool buttons for custom events in both calendar and `ADDED CLASSES`
image
image

### CODE REVIEW

**Review by KevinWu098 — APPROVED** [review]
LGTM; Looks like just a small merge conflict to deal with

**Comment by stevenguyukai** [comment]
I'm not sure why the test cann't pass. I think the test passed before [Update Settings Menu #810 ] is merged. @KevinWu098 do you know why this is the case? Also I need 1 approving review to merge 🤯

**Comment by KevinWu098** [comment]
> I'm not sure why the test cann't pass. I think the test passed before [Update Settings Menu #810 ] is merged. @KevinWu098 do you know why this is the case? Also I need 1 approving review to merge 🤯

Discussed it w/ Brian, it's a problem w/ JSDOM; We can go over it tomorrow morn, but for now I'm happy to merge this in

**Review by KevinWu098 — APPROVED** [review]
LGTM

**Pull request merged**
