### PR TITLE
Change out mapbox API token

### PR DESCRIPTION
**Pull request by EricPedley**
## Summary
Replaced invalid mapbox api token with a new one. When we get the chance we should figure out how to not publicly expose this but right now I don't care enough to figure it out.
## Test Plan
Make sure the map renders.

### CODE REVIEW

**Review by ap0nia — APPROVED** [review]
I can't check if the key actually works, but LGTM :pray:

**Review by Voark — APPROVED** [review]
We could move it to an env variable in the future potentially but also think this is fine for now. Just checked and the map shows up in staging.

**Comment by ap0nia** [comment]
> We could move it to an env variable in the future potentially but also think this is fine for now. Just checked and the map shows up in staging.

No that doesn't work because all env variables are statically replaced at build time; the final JavaScript bundle will inline all env variables we declare...front-end moment :tm:

It would just obfuscate the API key for somebody browsing the repo or contributing without the env file.

**Comment by Voark** [comment]
> > We could move it to an env variable in the future potentially but also think this is fine for now. Just checked and the map shows up in staging.
> 
> No that doesn't work because all env variables are statically replaced at build time; the final JavaScript bundle will inline all env variables we declare...front-end moment ™️
> 
> It would just obfuscate the API key for somebody browsing the repo or contributing without the env file.

You're right, imagine being able to think in the morning 😔

**Review by MinhxNguyen7 — APPROVED** [review]
Looks good; map renders.

**Pull request merged**
