### PR TITLE
Restyled custom events modal

### LINKED ISSUE #1025: Restyle Custom Events Modal
## Description
- This is ugly.
Image

### PR DESCRIPTION
**Pull request by xgraceyan**
## Summary
Fixed spacing and layout of event modal (Changed modal -> Previous modal)

image
image

Fixed responsive issue with day selector when using mobile view (After - Before)
image
image

## Test Plan
Make sure modal works properly and there are no visual issues on any viewport

## Issues
Building search variant is not consistent with the other inputs (filled vs. outlined); however, the filled version of building select looks better in its other appearance in the map view
Perhaps we could pass the variant as props to the component so the building select can be outlined in the custom events modal while also filled in the map view?

Closes #1025

### CODE REVIEW

**Comment by MinhxNguyen7** [comment]
@xgraceyan this looks ready for review. Is it? If not, no problem. Was just wondering.

**Comment by xgraceyan** [comment]
Yes, it's ready for review! Sorry, I forgot to change the status of the PR from a draft.

**Review by MinhxNguyen7 — APPROVED** [review]
LGTM!

**Comment by MinhxNguyen7** [comment]
I'll just comment that the "Issues" section in the PR description is for related GitHub issues. Issues with the PR itself should go in the description.
Also, I'll let it slide for now, but the "test plan" should be a little more detailed. E.g., check on 16x9 desktop, tablet, and small phone (Galaxy S8+).

**Pull request merged**
