### PR TITLE
deps: upgrade tsx

### LINKED ISSUE #1081: Fix build step in testing workflow
## Description
- The test step is failing, [e.g.](https://github.com/icssc/AntAlmanac/actions/runs/12451670866/job/34759820518?pr=1080)
- There seems to be a problem in the build step, likely introduced when we updated dependencies at some point.

image

### PR DESCRIPTION
**Pull request by KevinWu098**
## Summary
1. Upgrades `tsx` dependency, resolving a breaking change in Node which broke older versions of `tsx`

See: https://github.com/nodejs/node/issues/51048#issuecomment-1845927256

## Test Plan
1. Tests and deployment should run as expected

## Issues
Closes #1081 #1070

### CODE REVIEW

**Comment by KevinWu098** [comment]
@MinhxNguyen7 gonna need a key to be added to our secrets for tests to pass 🫡

**Comment by MinhxNguyen7** [comment]
You can actually add it to the build script, since that's a repository secret that is accessible from the workflow. You can see that because the workflow run shows the API key being available.

You should give it a try if you want to learn more about our devops. It's just one line. If you don't want to bother, I can do it.

**Comment by KevinWu098** [comment]
> You can actually add it to the build script, since that's a repository secret that is accessible from the workflow. You can see that because the workflow run shows the API key being available.
> 
> You should give it a try if you want to learn more about our devops. It's just one line. If you don't want to bother, I can do it.

Sorry, I'm not totally following -- I might be confused here, but I need repository-level access permissions to edit secrets, which I don't have

**Comment by KevinWu098** [comment]
Just checking in on this @MinhxNguyen7 -- the test workflow includes the secret so I'm rather confused about what's wrong or potentially misconfigured

**Comment by MinhxNguyen7** [comment]
Will look at this tomorrow

**Comment by MinhxNguyen7** [comment]
The secrets specified in the workflow (e.g., `secrets.ANTEATER_API_KEY`) have already been added to the repository. That's why the *deployments* work, including the build script. I'm figuring out, now, what the problem in the CI code is that fails to load the variables into the build environment.

**Comment by MinhxNguyen7** [comment]
After printing out all of the variables, it looks like none of the env vars specified in the workflow are making it into the backend build script. My guess is that, since the test workflow runs `pnpm build` instead of building the backend/frontend individually like the deployment workflows, the env vars are dropped by something along the chain, perhaps with turbo.

The flow is: test workflow -> build step -> `pnpm build` -> `turbo build`. After that, *I think* it runs `pnpm build` in `apps/backend`, which runs `pnpm prebuild` -> `pnpm get-search-data`...

@EricPedley @ap0nia if you wouldn't mind elucidating the issue, we'd appreciate it.

**Comment by ap0nia** [comment]
Just off the bat, have you tried messing with turborepo's configuration? https://turbo.build/repo/docs/crafting-your-repository/using-environment-variables

I'm on the road, and I can take a closer look once I'm back home.

**Comment by MinhxNguyen7** [comment]
> Just off the bat, have you tried messing with turborepo's configuration? https://turbo.build/repo/docs/crafting-your-repository/using-environment-variables

Will take a look

> I'm on the road, and I can take a closer look once I'm back home.

Don't worry about it too much.

**Comment by MinhxNguyen7** [comment]
Looks like the env vars are not even making it into the children of the initial `pnpm build`, after using `printenv` to check.

**Review by MinhxNguyen7 — APPROVED** [review]
```
                 |~
           |/    w
          / (   (|   \
         /( (/   |)  |\
  ____  ( (/    (|   | )  ,
 |----\ (/ |    /|   |'\ /^;
\---*---Y--+-----+---+--/(
 \------*---*--*---*--/
  '~~ ~~~~~~~~~~~~~~~
```

**Pull request merged**
